iRRAM: iRRAM::internal::run Class Reference
iRRAM::internal::run Class Reference
#include <lib.h>
Public Member Functions
run (state_t &st)
~run ()
template<typename F , typename... Args>
ret_void_t< F, Args... > exec (F f, const Args &... args)
template<typename F , typename... Args>
ret_value_t< F, Args... > exec (F f, const Args &... args)
Detailed Description
Definition at line 83 of file lib.h.
Constructor & Destructor Documentation
run()
iRRAM::internal::run::run (state_t & st)
Definition at line 159 of file REALmain.cc.
References iRRAM::ITERATION_DATA::actual_prec, iRRAM::state_t::ACTUAL_STACK, iRRAM::actual_stack(), iRRAM::state_t::cache_active, iRRAM::state_t::cache_address, iRRAM::cerr, iRRAM::cout, iRRAM::state_t::debug, iRRAM::state_t::highlevel, iRRAM::cachelist::id, iRRAM::stiff::inc_step(), iRRAM::ITERATION_DATA::inlimit, iRRAM::state_t::inReiterate, iRRAM_DEFAULT_PREC_START, iRRAM_unlikely, iRRAM_VERSION_rt, iRRAM::state_t::max_active, iRRAM::state_t::max_prec, iRRAM::ITERATION_DATA::prec_policy, iRRAM::state_t::prec_skip, iRRAM::ITERATION_DATA::prec_step, iRRAM::cache_type::rewind(), iRRAM::orstream::rewind(), and iRRAM::show_statistics().
~run()
iRRAM::internal::run::~run ()
Definition at line 225 of file REALmain.cc.
References iRRAM::state_t::cache_active, iRRAM::state_t::cache_address, iRRAM::cerr, iRRAM::cache_type::clear(), iRRAM::cout, iRRAM::state_t::debug, iRRAM::cachelist::id, iRRAM_unlikely, iRRAM::state_t::max_active, iRRAM::orstream::reset(), and iRRAM::show_statistics().
Member Function Documentation
exec() [1/2]
template<typename F , typename... Args> ret_void_t<F,Args...> iRRAM::internal::run::exec (F f, const Args &... args) inline
Definition at line 95 of file lib.h.
References iRRAM::ITERATION_DATA::actual_prec, iRRAM::state_t::ACTUAL_STACK, iRRAM::actual_stack(), iRRAM::cerr, iRRAM::state_t::infinite, iRRAM_error_msg, iRRAM_likely, iRRAM::Iteration::prec_diff, and iRRAM::iRRAM_Numerical_Exception::type.
Referenced by exec(), iRRAM::exec(), and iRRAM_exec().
exec() [2/2]
template<typename F , typename... Args> ret_value_t<F,Args...> iRRAM::internal::run::exec (F f, const Args &... args) inline
Definition at line 120 of file lib.h.
References exec().
The documentation for this class was generated from the following files:
include/iRRAM/lib.h
src/REALmain.cc