iRRAM: Debug
Debug
Functions
void iRRAM::limit_debug (const char *c)
void iRRAM::limit_debug2 (const char *c)
void iRRAM::REAL::rcheck (int n=50) const
Detailed Description
Function Documentation
limit_debug()
void iRRAM::limit_debug (const char * c) inline
Definition at line 149 of file limit_templates.h.
References iRRAM::actual_stack(), iRRAM::cerr, iRRAM_unlikely, iRRAM::ITERATION_DATA::prec_step, and iRRAM::state.
Referenced by iRRAM::limit(), iRRAM::limit_hint(), iRRAM::limit_lip(), and iRRAM::limit_mv().
limit_debug2()
void iRRAM::limit_debug2 (const char * c) inline
Definition at line 159 of file limit_templates.h.
References iRRAM::ITERATION_DATA::actual_prec, iRRAM::actual_stack(), iRRAM::cerr, iRRAM_unlikely, iRRAM::ITERATION_DATA::prec_step, and iRRAM::state.
Referenced by iRRAM::limit(), and iRRAM::limit_lip().
rcheck()
void iRRAM::REAL::rcheck (int n = 50) const
Definition at line 835 of file REALS.cc.
References iRRAM::cerr, iRRAM::REAL::dp, iRRAM::REAL::error, iRRAM::generic_sizetype< M, E >::exponent, iRRAM::generic_sizetype< M, E >::mantissa, MP_swrite, iRRAM::REAL::value, and iRRAM::REAL::vsize.