iRRAM: src/MPFR/MPFR_ext.h File Reference
MPFR_ext.h File Reference
#include <stdlib.h>
#include <stdio.h>
#include <inttypes.h>
#include <iRRAM/MPFR_interface.h>
#include <mpfr.h>
Macros
#define __STDC_FORMAT_MACROS 1
#define mpfr_get_prec(x) ((x)->_mpfr_prec)
#define mpfr_get_exp(x) ((x)->_mpfr_exp)
#define MPFR_MANT(x) ((x)->_mpfr_d)
#define MPFR_LIMB_SIZE(x) (MPFR_MSW_INDEX(x) + 1)
#define MPFR_NOTZERO(x) !(mpfr_sgn(x)==0)
#define MPFR_MSW_INDEX(x) ((mpfr_get_prec(x)-1)/BITS_PER_MP_LIMB)
#define MAX_OF(h, i) ((h) >= (i) ? (h) : (i))
#define GMP_min -1000000000
#define GMP_max 1000000000
#define iRRAM_mpfr_rounding_mode GMP_RNDN
Functions
int ext_mpfr_size (const mpfr_t z)
void ext_mpfr_add (const mpfr_t z1, const mpfr_t z2, mpfr_t z, int p)
void ext_mpfr_sub (const mpfr_t z1, const mpfr_t z2, mpfr_t z, int p)
void ext_mpfr_mul (const mpfr_t z1, const mpfr_t z2, mpfr_t z, int p)
void ext_mpfr_div (const mpfr_t z1, const mpfr_t z2, mpfr_t z, int p)
void ext_mpfr_abs (const mpfr_t z1, mpfr_t z)
void ext_mpfr_truncate (const mpfr_t z1, mpfr_t z)
void ext_mpfr_set_z (mpfr_t r, int_mpfr_type i)
void ext_mpfr_set_f2i (mpfr_t r, int_mpfr_type i)
void ext_mpfr_add_i (const mpfr_t z1, int z2, mpfr_t z, int p)
void ext_mpfr_sub_i (const mpfr_t z1, int z2, mpfr_t z, int p)
void ext_mpfr_i_sub (int z1, const mpfr_t z2, mpfr_t z, int p)
void ext_mpfr_mul_i (const mpfr_t z1, int z2, mpfr_t z, int p)
void ext_mpfr_div_i (const mpfr_t z1, int z2, mpfr_t z, int p)
void ext_mpfr_i_div (int z1, const mpfr_t z2, mpfr_t z, int p)
void ext_mpfr_writee (const mpfr_t z, int w)
char * ext_mpfr_swritee (const mpfr_t z, int w)
void ext_mpfr_write (const mpfr_t z, int w)
void ext_mpfr_duplicate_w_init (const mpfr_t z1, mpfr_ptr *z2)
void ext_mpfr_duplicate_wo_init (const mpfr_t z1, mpfr_t z2)
void ext_mpfr_sqrt (const mpfr_t z1, mpfr_t z, int p)
void ext_mpfr_shift (const mpfr_t z1, mpfr_t z, int p)
void ext_mpfr_remove_trailing_zeroes (mpfr_t x)
void ext_mpfr_getsize (const mpfr_t z, ext_mpfr_sizetype *s)
Macro Definition Documentation
__STDC_FORMAT_MACROS
#define __STDC_FORMAT_MACROS 1
Definition at line 31 of file MPFR_ext.h.
GMP_max
#define GMP_max 1000000000
Definition at line 66 of file MPFR_ext.h.
GMP_min
#define GMP_min -1000000000
Definition at line 65 of file MPFR_ext.h.
Referenced by ext_mpfr_getsize(), and ext_mpfr_size().
iRRAM_mpfr_rounding_mode
#define iRRAM_mpfr_rounding_mode GMP_RNDN
Definition at line 68 of file MPFR_ext.h.
Referenced by ext_mpfr_abs(), ext_mpfr_add(), ext_mpfr_add_i(), ext_mpfr_div(), ext_mpfr_div_i(), ext_mpfr_duplicate_wo_init(), ext_mpfr_i_div(), ext_mpfr_i_sub(), ext_mpfr_mul(), ext_mpfr_mul_i(), ext_mpfr_set_z(), ext_mpfr_shift(), ext_mpfr_sqrt(), ext_mpfr_sub(), ext_mpfr_sub_i(), ext_mpfr_swritee(), ext_mpfr_write(), and ext_mpfr_writee().
MAX_OF
#define MAX_OF (h, i) ((h) >= (i) ? (h) : (i))
Definition at line 63 of file MPFR_ext.h.
Referenced by ext_mpfr_add(), ext_mpfr_add_i(), ext_mpfr_div(), ext_mpfr_div_i(), ext_mpfr_i_div(), ext_mpfr_i_sub(), ext_mpfr_mul(), ext_mpfr_set_z(), ext_mpfr_sqrt(), ext_mpfr_sub(), and ext_mpfr_sub_i().
mpfr_get_exp
#define mpfr_get_exp (x) ((x)->_mpfr_exp)
Definition at line 55 of file MPFR_ext.h.
Referenced by ext_mpfr_getsize(), and ext_mpfr_size().
mpfr_get_prec
#define mpfr_get_prec (x) ((x)->_mpfr_prec)
Definition at line 52 of file MPFR_ext.h.
Referenced by ext_mpfr_abs(), ext_mpfr_duplicate_wo_init(), ext_mpfr_mul_i(), ext_mpfr_shift(), ext_mpfr_swritee(), ext_mpfr_truncate(), ext_mpfr_write(), and mpfr_wrapper().
MPFR_LIMB_SIZE
#define MPFR_LIMB_SIZE (x) (MPFR_MSW_INDEX(x) + 1)
Definition at line 59 of file MPFR_ext.h.
Referenced by ext_mpfr_write().
MPFR_MANT
#define MPFR_MANT (x) ((x)->_mpfr_d)
Definition at line 58 of file MPFR_ext.h.
Referenced by ext_mpfr_remove_trailing_zeroes().
MPFR_MSW_INDEX
#define MPFR_MSW_INDEX (x) ((mpfr_get_prec(x)-1)/BITS_PER_MP_LIMB)
Definition at line 61 of file MPFR_ext.h.
Referenced by ext_mpfr_getsize(), and ext_mpfr_remove_trailing_zeroes().
MPFR_NOTZERO
#define MPFR_NOTZERO (x) !(mpfr_sgn(x)==0)
Definition at line 60 of file MPFR_ext.h.
Referenced by ext_mpfr_getsize(), and ext_mpfr_size().
Function Documentation
ext_mpfr_abs()
void ext_mpfr_abs (const mpfr_t z1, mpfr_t z) inline
Definition at line 273 of file MPFR_ext.h.
References iRRAM_mpfr_rounding_mode, and mpfr_get_prec.
ext_mpfr_add()
void ext_mpfr_add (const mpfr_t z1, const mpfr_t z2, mpfr_t z, int p) inline
Definition at line 148 of file MPFR_ext.h.
References ext_mpfr_remove_trailing_zeroes(), ext_mpfr_size(), iRRAM_mpfr_rounding_mode, and MAX_OF.
ext_mpfr_add_i()
void ext_mpfr_add_i (const mpfr_t z1, int z2, mpfr_t z, int p) inline
Definition at line 160 of file MPFR_ext.h.
References BITS_PER_MP_LIMB, ext_mpfr_size(), iRRAM_mpfr_rounding_mode, and MAX_OF.
ext_mpfr_div()
void ext_mpfr_div (const mpfr_t z1, const mpfr_t z2, mpfr_t z, int p) inline
Definition at line 235 of file MPFR_ext.h.
References ext_mpfr_remove_trailing_zeroes(), ext_mpfr_size(), iRRAM_mpfr_rounding_mode, and MAX_OF.
ext_mpfr_div_i()
void ext_mpfr_div_i (const mpfr_t z1, int z2, mpfr_t z, int p) inline
Definition at line 247 of file MPFR_ext.h.
References ext_mpfr_size(), iRRAM_mpfr_rounding_mode, and MAX_OF.
ext_mpfr_duplicate_w_init()
void ext_mpfr_duplicate_w_init (const mpfr_t z1, mpfr_ptr * z2)
ext_mpfr_duplicate_wo_init()
void ext_mpfr_duplicate_wo_init (const mpfr_t z1, mpfr_t z2) inline
Definition at line 425 of file MPFR_ext.h.
References iRRAM_mpfr_rounding_mode, and mpfr_get_prec.
ext_mpfr_getsize()
void ext_mpfr_getsize (const mpfr_t z, ext_mpfr_sizetype * s) inline
From the multiple precicion representation of a dyadic number \(z\) extract \(m\in\mathbb N,e\in\mathbb Z:(m-1)\cdot2^e\leq|z|<m\cdot2^e\). Additionally, \(z=0\iff m=0\).
Parameters
[in] z
[out] s pointer to a sizetype which gets assigned a value \(m\cdot2^e\) bounding \(|z|\)
Definition at line 129 of file MPFR_ext.h.
References BITS_PER_MP_LIMB, ext_mpfr_sizetype::exponent, GMP_min, ext_mpfr_sizetype::mantissa, mpfr_get_exp, MPFR_MSW_INDEX, and MPFR_NOTZERO.
ext_mpfr_i_div()
void ext_mpfr_i_div (int z1, const mpfr_t z2, mpfr_t z, int p) inline
Definition at line 260 of file MPFR_ext.h.
References BITS_PER_MP_LIMB, ext_mpfr_size(), iRRAM_mpfr_rounding_mode, and MAX_OF.
ext_mpfr_i_sub()
void ext_mpfr_i_sub (int z1, const mpfr_t z2, mpfr_t z, int p) inline
Definition at line 197 of file MPFR_ext.h.
References BITS_PER_MP_LIMB, ext_mpfr_size(), iRRAM_mpfr_rounding_mode, and MAX_OF.
ext_mpfr_mul()
void ext_mpfr_mul (const mpfr_t z1, const mpfr_t z2, mpfr_t z, int p) inline
Definition at line 209 of file MPFR_ext.h.
References ext_mpfr_remove_trailing_zeroes(), ext_mpfr_size(), iRRAM_mpfr_rounding_mode, and MAX_OF.
ext_mpfr_mul_i()
void ext_mpfr_mul_i (const mpfr_t z1, int z2, mpfr_t z, int p) inline
Definition at line 221 of file MPFR_ext.h.
References BITS_PER_MP_LIMB, ext_mpfr_size(), iRRAM_mpfr_rounding_mode, and mpfr_get_prec.
ext_mpfr_remove_trailing_zeroes()
void ext_mpfr_remove_trailing_zeroes (mpfr_t x) inline
Definition at line 99 of file MPFR_ext.h.
References BITS_PER_MP_LIMB, MPFR_MANT, and MPFR_MSW_INDEX.
Referenced by ext_mpfr_add(), ext_mpfr_div(), ext_mpfr_mul(), ext_mpfr_sqrt(), ext_mpfr_sub(), and iRRAM::strtoREAL2().
ext_mpfr_set_f2i()
void ext_mpfr_set_f2i (mpfr_t r, int_mpfr_type i)
ext_mpfr_set_z()
void ext_mpfr_set_z (mpfr_t r, int_mpfr_type i) inline
Definition at line 452 of file MPFR_ext.h.
References iRRAM_mpfr_rounding_mode, and MAX_OF.
ext_mpfr_shift()
void ext_mpfr_shift (const mpfr_t z1, mpfr_t z, int p) inline
Definition at line 443 of file MPFR_ext.h.
References iRRAM_mpfr_rounding_mode, and mpfr_get_prec.
ext_mpfr_size()
int ext_mpfr_size (const mpfr_t z) inline
Definition at line 114 of file MPFR_ext.h.
References GMP_min, mpfr_get_exp, and MPFR_NOTZERO.
Referenced by ext_mpfr_add(), ext_mpfr_add_i(), ext_mpfr_div(), ext_mpfr_div_i(), ext_mpfr_i_div(), ext_mpfr_i_sub(), ext_mpfr_mul(), ext_mpfr_mul_i(), ext_mpfr_sqrt(), ext_mpfr_sub(), and ext_mpfr_sub_i().
ext_mpfr_sqrt()
void ext_mpfr_sqrt (const mpfr_t z1, mpfr_t z, int p) inline
Definition at line 432 of file MPFR_ext.h.
References ext_mpfr_remove_trailing_zeroes(), ext_mpfr_size(), iRRAM_mpfr_rounding_mode, and MAX_OF.
ext_mpfr_sub()
void ext_mpfr_sub (const mpfr_t z1, const mpfr_t z2, mpfr_t z, int p) inline
Definition at line 173 of file MPFR_ext.h.
References ext_mpfr_remove_trailing_zeroes(), ext_mpfr_size(), iRRAM_mpfr_rounding_mode, and MAX_OF.
ext_mpfr_sub_i()
void ext_mpfr_sub_i (const mpfr_t z1, int z2, mpfr_t z, int p) inline
Definition at line 185 of file MPFR_ext.h.
References BITS_PER_MP_LIMB, ext_mpfr_size(), iRRAM_mpfr_rounding_mode, and MAX_OF.
ext_mpfr_swritee()
char * ext_mpfr_swritee (const mpfr_t z, int w) inline
Definition at line 306 of file MPFR_ext.h.
References iRRAM_mpfr_rounding_mode, and mpfr_get_prec.
ext_mpfr_truncate()
void ext_mpfr_truncate (const mpfr_t z1, mpfr_t z) inline
Definition at line 281 of file MPFR_ext.h.
References mpfr_get_prec.
ext_mpfr_write()
void ext_mpfr_write (const mpfr_t z, int w) inline
Definition at line 404 of file MPFR_ext.h.
References iRRAM_mpfr_rounding_mode, mpfr_get_prec, and MPFR_LIMB_SIZE.
ext_mpfr_writee()
void ext_mpfr_writee (const mpfr_t z, int w) inline
Definition at line 290 of file MPFR_ext.h.
References iRRAM_mpfr_rounding_mode.