iRRAM: src/MPFR/mpfr_extension.cc File Reference
mpfr_extension.cc File Reference
#include <iRRAM/lib.h>
#include <iRRAM/mpfr_extension.h>
#include "MPFR_ext.h"
Typedefs
typedef DYADIC() DYADIC_function(const DYADIC &, const int &)
Functions
void mpfr_wrapper (DYADIC_function f, mpfr_ptr r, mpfr_srcptr u, int p)
void mpfr_ext_test (mpfr_ptr y, mpfr_srcptr u, int p, mp_rnd_t rnd_mode)
void mpfr_ext_exp (mpfr_ptr r, mpfr_srcptr u, int p)
void mpfr_ext_log (mpfr_ptr r, mpfr_srcptr u, int p)
void mpfr_ext_sin (mpfr_ptr r, mpfr_srcptr u, int p)
void mpfr_ext_cos (mpfr_ptr r, mpfr_srcptr u, int p)
void mpfr_ext_tan (mpfr_ptr r, mpfr_srcptr u, int p)
Typedef Documentation
DYADIC_function
typedef DYADIC() DYADIC_function(const DYADIC &, const int &)
Definition at line 32 of file mpfr_extension.cc.
Function Documentation
mpfr_ext_cos()
void mpfr_ext_cos (mpfr_ptr r, mpfr_srcptr u, int p)
Definition at line 73 of file mpfr_extension.cc.
References mpfr_wrapper().
mpfr_ext_exp()
void mpfr_ext_exp (mpfr_ptr r, mpfr_srcptr u, int p)
Definition at line 64 of file mpfr_extension.cc.
References mpfr_wrapper().
mpfr_ext_log()
void mpfr_ext_log (mpfr_ptr r, mpfr_srcptr u, int p)
Definition at line 67 of file mpfr_extension.cc.
References mpfr_wrapper().
mpfr_ext_sin()
void mpfr_ext_sin (mpfr_ptr r, mpfr_srcptr u, int p)
Definition at line 70 of file mpfr_extension.cc.
References mpfr_wrapper().
mpfr_ext_tan()
void mpfr_ext_tan (mpfr_ptr r, mpfr_srcptr u, int p)
Definition at line 76 of file mpfr_extension.cc.
References mpfr_wrapper().
mpfr_ext_test()
void mpfr_ext_test (mpfr_ptr y, mpfr_srcptr u, int p, mp_rnd_t rnd_mode)
Definition at line 46 of file mpfr_extension.cc.
References mpfr_wrapper().
mpfr_wrapper()
void mpfr_wrapper (DYADIC_function f, mpfr_ptr r, mpfr_srcptr u, int p) inline
Definition at line 34 of file mpfr_extension.cc.
References iRRAM::arg(), iRRAM::exec(), mpfr_get_prec, iRRAM::DYADIC::value, and iRRAM::REAL::value.
Referenced by mpfr_ext_cos(), mpfr_ext_exp(), mpfr_ext_log(), mpfr_ext_sin(), mpfr_ext_tan(), and mpfr_ext_test().