iRRAM: src/REALmain.cc File Reference
REALmain.cc File Reference
#include <cmath>
#include <cstdlib>
#include <cstdarg>
#include <cstring>
#include <vector>
#include <cfenv>
#include <iRRAM/lib.h>
#include <sys/time.h>
#include <sys/resource.h>
#include <unistd.h>
Namespaces
iRRAM
Functions
void iRRAM::show_statistics ()
int iRRAM_exec (void(*f)(void *), void *data)
int iRRAM_parse_args (struct iRRAM_init_options *opts, int *argc, char **argv)
void iRRAM_initialize3 (const struct iRRAM_init_options *_opts)
void iRRAM_initialize2 (int *argc, char **argv)
like iRRAM_initialize(), but modifies its arguments as to remove parsed options pertaining iRRAM.
void iRRAM_initialize (int argc, char **argv)
void iRRAM_finalize ()
Variables
iRRAM_TLS state_proxy< iRRAM_HAVE_TLS > iRRAM::state
iRRAM_TLS orstream iRRAM::cout
iRRAM_TLS irstream iRRAM::cin
Function Documentation
iRRAM_exec()
int iRRAM_exec (void(*)(void *) f, void * data)
Definition at line 264 of file REALmain.cc.
References iRRAM::exec(), and iRRAM::iRRAM_Numerical_Exception::type.
iRRAM_finalize()
void iRRAM_finalize (void)
Definition at line 376 of file REALmain.cc.
Referenced by main().
iRRAM_initialize()
void iRRAM_initialize (int argc, char ** argv)
Definition at line 370 of file REALmain.cc.
References iRRAM_initialize2().
iRRAM_initialize2()
void iRRAM_initialize2 (int * argc, char ** argv)
like iRRAM_initialize(), but modifies its arguments as to remove parsed options pertaining iRRAM.
Definition at line 362 of file REALmain.cc.
Referenced by iRRAM_initialize(), and main().
iRRAM_initialize3()
void iRRAM_initialize3 (const struct iRRAM_init_options * _opts)
Definition at line 356 of file REALmain.cc.
References iRRAM::internal::init().
iRRAM_parse_args()
int iRRAM_parse_args (struct iRRAM_init_options * opts, int * argc, char ** argv)
Definition at line 274 of file REALmain.cc.