iRRAM: iRRAM::internal::wrap_type< T, clearfct > Struct Template Reference
iRRAM::internal::wrap_type< T, clearfct > Struct Template Reference
#include <cache.h>
Public Member Functions
wrap_type () noexcept(noexcept(T()))
wrap_type (const T &v) noexcept(noexcept(T(v)))
wrap_type (wrap_type &&o) noexcept(noexcept(std::swap(v, o.v)))
~wrap_type () noexcept
wrap_type & operator= (const T &_v) noexcept(noexcept(const_cast< T &>(_v)=_v))
wrap_type & operator= (wrap_type o) noexcept(noexcept(std::swap(v, o.v)))
operator T () const noexcept
Public Attributes
T v
Detailed Description
template<typename T, void(*)(T &) clearfct>
struct iRRAM::internal::wrap_type< T, clearfct >
Definition at line 36 of file cache.h.
Constructor & Destructor Documentation
wrap_type() [1/3]
template<typename T , void(*)(T &) clearfct> iRRAM::internal::wrap_type< T, clearfct >::wrap_type () inline noexcept
Definition at line 39 of file cache.h.
wrap_type() [2/3]
template<typename T , void(*)(T &) clearfct> iRRAM::internal::wrap_type< T, clearfct >::wrap_type (const T & v) inline noexcept
Definition at line 41 of file cache.h.
wrap_type() [3/3]
template<typename T , void(*)(T &) clearfct> iRRAM::internal::wrap_type< T, clearfct >::wrap_type (wrap_type< T, clearfct > && o) inline noexcept
Definition at line 43 of file cache.h.
References iRRAM::swap(), and iRRAM::internal::wrap_type< T, clearfct >::v.
~wrap_type()
template<typename T , void(*)(T &) clearfct> iRRAM::internal::wrap_type< T, clearfct >::~wrap_type () inline noexcept
Definition at line 47 of file cache.h.
References iRRAM::internal::wrap_type< T, clearfct >::v.
Member Function Documentation
operator T()
template<typename T , void(*)(T &) clearfct> iRRAM::internal::wrap_type< T, clearfct >::operator T () const inline noexcept
Definition at line 55 of file cache.h.
References iRRAM::internal::wrap_type< T, clearfct >::v.
operator=() [1/2]
template<typename T , void(*)(T &) clearfct> wrap_type& iRRAM::internal::wrap_type< T, clearfct >::operator= (const T & _v) inline noexcept
Definition at line 49 of file cache.h.
References iRRAM::internal::wrap_type< T, clearfct >::v.
operator=() [2/2]
template<typename T , void(*)(T &) clearfct> wrap_type& iRRAM::internal::wrap_type< T, clearfct >::operator= (wrap_type< T, clearfct > o) inline noexcept
Definition at line 52 of file cache.h.
References iRRAM::swap(), and iRRAM::internal::wrap_type< T, clearfct >::v.
Member Data Documentation
v
template<typename T , void(*)(T &) clearfct> T iRRAM::internal::wrap_type< T, clearfct >::v
Definition at line 37 of file cache.h.
Referenced by iRRAM::internal::wrap_type< T, clearfct >::operator T(), iRRAM::internal::wrap_type< T, clearfct >::operator=(), iRRAM::internal::wrap_type< T, clearfct >::wrap_type(), and iRRAM::internal::wrap_type< T, clearfct >::~wrap_type().
The documentation for this struct was generated from the following file:
include/iRRAM/cache.h